name: Deploy to Firebase Hosting on merge (Live Channel)

on:
  push:
    branches:
      - main # <--- ¡IMPORTANTE! Cambia 'main' si tu rama principal es diferente (ej. 'master')

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Instala dependencias y construye tu aplicación
      - name: Install dependencies and build
        run: npm ci && npm run build # <--- Comando de construcción que seleccionaste

      # Despliega a Firebase Hosting
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ACCESSPDF }}' # <--- ¡IMPORTANTE! Asegúrate que el ID del proyecto sea el tuyo
          projectId: accesspdf # <--- ¡IMPORTANTE! Reemplaza 'accesspdf' con el ID de tu proyecto Firebase
          channelId: live # Despliega al canal en vivo